var tabledata = [{
    id: 1,
    usecasetype: "Code and IT development",
    worktitle: "SAS to R translation",
    link: "https://unece.org/sites/default/files/2023-12/HLGMOS%20LLM%20Paper_Preprint_1.pdf",
    resourcetype: "Paper",
    organisation: "CSO Ireland",
    date: "2023-12",
    aimodels: "GPT-3.5",
    approach: " ",
    tools: " ",
    codeavailability: ""
},
{
    id: 2,
    usecasetype: "Code and IT development",
    worktitle: "SAS to R conversion: the use of LLM",
    link: "https://my.visme.co/view/z4nodvzv-gpt-for-sas-to-r-slides-for-geneva#s1",
    resourcetype: "Presentation",
    organisation: "France Insee",
    date: "2023-11",
    aimodels: "GPT-3.5",
    approach: " ",
    tools: " ",
    codeavailability: ""
},
{
    id: 3,
    usecasetype: "Text generation for analysis",
    worktitle: "Report Generation Using LLMs",
    link: "https://unece.org/sites/default/files/2023-12/HLGMOS%20LLM%20Paper_Preprint_1.pdf",
    resourcetype: "Paper",
    organisation: "Statistics Canada",
    date: "2023-11",
    aimodels: "GPT-3.5, GPT-4, Llama 2",
    approach: "Zero-shot draft generation",
    tools: "Azure OpenAI Service, Arthur AI Bench",
    codeavailability: ""
},
{
    id: 4,
    usecasetype: "Text generation for analysis",
    worktitle: "AI in Statistics Norway",
    link: "Resources/StatisticsNorway_2024_05_Comm.pdf", 
    resourcetype: "Presentation",
    organisation: "Statistics Norway",
    date: "2024-05",
    aimodels: "GPT-4",
    approach: "Prompt engineering",
    tools: "Chat GPT",
    codeavailability: "N/A"
},
{
    id: 5,
    usecasetype: "Text generation for data processing (editing)",
    worktitle: "Leveraging AI-assistants for better metadata and communication",
    link: "https://unece.org/sites/default/files/2023-12/HLGMOS%20LLM%20Paper_Preprint_1.pdf", 
    resourcetype: "Presentation",
    organisation: "Bank of International Settlements",
    date: "2024-03",
    aimodels: "GPT-3.5",
    approach: "Prompt engineering, RAG",
    tools: "OpenAI AI Assistant",
    codeavailability: "N/A"
},
{
    id: 6,
    usecasetype: "Text generation for data processing (editing)",
    worktitle: "Leveraging AI-assistants for better metadata and communication",
    link: "Resources/BIS_2024_04_MetadataEditing.pdf",
    resourcetype: "Presentation",
    organisation: "Bank of International Settlements",
    date: "2024-03",
    aimodels: "GPT-3.5",
    approach: "Prompt engineering, RAG",
    tools: "OpenAI AI Assistant",
    codeavailability: "N/A"
},
{
    id: 7,
    usecasetype: "Communication - textual materials",
    worktitle: "Use of AI in the communication and dissemination of statistics",
    link: "Resources/StatisticsIndonesia_2024_03_Comm.pdf", 
    resourcetype: "Presentation",
    organisation: "Statistics Indonesia",
    date: "2024-03",
    aimodels: "GPT-3.5",
    approach: "Prompt engineering",
    tools: " ",
    codeavailability: "N/A"
},
{
    id: 8,
    usecasetype: "Communication - images or videos materials",
    worktitle: "Use of Generative AI in ESTAT",
    link: "",
    resourcetype: "Presentation",
    organisation: "EUROSTAT",
    date: "2024-04",
    aimodels: " ",
    approach: "Prompt engineering",
    tools: "DALL.E, ChatGPT, Adobe Firefly, Image Creator, Midjourney",
    codeavailability: "N/A"
},
{
    id: 9,
    usecasetype: "Data dissemination and information search",
    worktitle: "Free to play: UNCTAD's experience with developing its own open-source RAG LLM application",
    link: "https://unece.org/sites/default/files/2024-05/ECE_CES_2024_23_E.pdf",
    resourcetype: "Paper",
    organisation: "UNCTAD",
    date: "2024-05",
    aimodels: "mistral",
    approach: "RAG",
    tools: "LlamaIndex, PostgreSQL, Streamlit",
    codeavailability: "Yes"
},
{
    id: 10,
    usecasetype: "Data dissemination and information search",
    worktitle: "Free to play: UNCTAD's experience with developing its own open-source RAG LLM application",
    link: "https://unece.org/sites/default/files/2024-06/5_2_4_AI%20and%20LLM_UNCTAD_DanielHopp.pdf",
    resourcetype: "Presentation",
    organisation: "UNCTAD",
    date: "2024-04",
    aimodels: "mistral",
    approach: "RAG",
    tools: "LlamaIndex, PostgreSQL, Streamlit",
    codeavailability: "Yes"
},
{
    id: 11,
    usecasetype: "Data dissemination and information search",
    worktitle: "Using large language models (LLMs) to improve website search experience with StatsChat ",
    link: "https://datasciencecampus.ons.gov.uk/using-large-language-models-llms-to-improve-website-search-experience-with-statschat/",
    resourcetype: "Blog",
    organisation: "UK ONS",
    date: "2023-08",
    aimodels: "Flan-T5; all-mpnet-base-v2",
    approach: "RAG",
    tools: " ",
    codeavailability: "Yes"
},
{
    id: 12,
    usecasetype: "Data dissemination and information search",
    worktitle: "Statbot.Swiss A Chatbot to query Swiss Open Data",
    link: "Resources/SwissFSO_2024_07_Statbot.pdf",
    resourcetype: "Presentation",
    organisation: "Switzerland FSO",
    date: "2024-06",
    aimodels: "GPT-3.5 Turbo, mixtral-8x7b-instruct",
    approach: "Text-to-SQL, In-Context Learning",
    tools: " ",
    codeavailability: "Yes"
},
{
    id: 13,
    usecasetype: "Data dissemination and information search",
    worktitle: "Statbot.Swiss A Chatbot to query Swiss Open Data",
    link: "https://arxiv.org/abs/2406.03170",
    resourcetype: "Paper",
    organisation: "Switzerland FSO",
    date: "2024-06",
    aimodels: "GPT-3.5 Turbo, mixtral-8x7b-instruct",
    approach: "Text-to-SQL, In-Context Learning",
    tools: " ",
    codeavailability: "Yes"
},
{
    id: 14,
    usecasetype: "Data dissemination and information search, Communication - images or videos materials",
    worktitle: "Text based intelligent assistant: TIA",
    link: "Resources/GermanCentralBank_2024_06_Comm.pdf", 
    resourcetype: "Presentation",
    organisation: "Bundesbank Germany",
    date: "2024-06",
    aimodels: "GPT-3.5, GPT-4 Turbo, GPT-4",
    approach: "Prompt engineering ",
    tools: "Chat GPT via Azure Microsoft Cloud Service",
    codeavailability: " "
},
{
    id: 15,
    usecasetype: "Data dissemination and information search",
    worktitle: "Stat GPT - Exploring Official Statistics using Generative AI and SDMX",
    link: "https://unece.org/sites/default/files/2024-06/5_2_3_AI%20and%20LLM_IMF_BertKroese.pdf",
    resourcetype: "Presentation",
    organisation: "IMF",
    date: "2024-06",
    aimodels: "",
    approach: "Multi agent",
    tools: "",
    codeavailability: " "
},
{
    id: 16,
    usecasetype: "Data dissemination and information search",
    worktitle: "Stat GPT - Exploring Official Statistics using Generative AI and SDMX",
    link: "https://unece.org/sites/default/files/2023-12/HLGMOS%20LLM%20Paper_Preprint_1.pdf",
    resourcetype: "Paper",
    organisation: "IMF",
    date: "2023-11",
    aimodels: "GPT-3.5, GPT-4",
    approach: "",
    tools: "AI-Dial",
    codeavailability: " "
},
{
    id: 17,
    usecasetype: "Text generation for data processing",
    worktitle: "Updating Statistical Classification Definitions",
    link: "https://unece.org/sites/default/files/2023-12/HLGMOS%20LLM%20Paper_Preprint_1.pdf",
    resourcetype: "Paper",
    organisation: "Australian Bureau of Statistics",
    date: "2023-11",
    aimodels: "",
    approach: "",
    tools: "",
    codeavailability: " "
},
{
    id: 18,
    usecasetype: "Data dissemination and information search",
    worktitle: "Adopting artificial intelligence in the production and dissemination of official statistics",
    link: "https://unece.org/sites/default/files/2024-05/ECE_CES_2024_21_E.pdf",
    resourcetype: "Paper",
    organisation: "Statistics Norway",
    date: "2024-05",
    aimodels: "",
    approach: "RAG",
    tools: "LangChain, Chainlit, PandasAI",
    codeavailability: " "
},
{
    id: 19,
    usecasetype: "Text generation for data processing",
    worktitle: "ClassifAI – Exploring the use of Large Language Models (LLMs) to assign free text to commonly used classifications",
    link: "https://datasciencecampus.ons.gov.uk/classifai-exploring-the-use-of-large-language-models-llms-to-assign-free-text-to-commonly-used-classifications/",
    resourcetype: "Blog",
    organisation: "UK ONS",
    date: "2024-07",
    aimodels: "MiniLM, Gemini-Pro",
    approach: "RAG",
    tools: "LangChain, Streamlit",
    codeavailability: "Yes"
},
{
    id: 20,
    usecasetype: "Data dissemination and information search",
    worktitle: "Beyond keywords: AI-driven approaches to improve data discoverability",
    link: "https://blogs.worldbank.org/en/opendata/beyond-keywords--ai-driven-approaches-to-improve-data-discoverab0",
    resourcetype: "Blog",
    organisation: "World Bank",
    date: "2024-05",
    aimodels: "GIST-all-MiniLM-L6-v2",
    approach: " ",
    tools: " ",
    codeavailability: " "
},
{
    id: 21,
    usecasetype: "Communication - images or videos materials",
    worktitle: "AI tools and video generation process",
    link: "https://vimeo.com/statcanvideo/review/982142762/57e7b37f68",
    resourcetype: "Video demo",
    organisation: "Statistics Canada",
    date: "2024-07",
    aimodels: "GIST-all-MiniLM-L6-v2",
    approach: " ",
    tools: "HeyGen, ElevenLabs, ChatGPT, Hedra, Suno",
    codeavailability: "N/A"
},
{
    id: 22,
    usecasetype: "Data dissemination and information search",
    worktitle: "SDMX + AI: A path to explore generative AI for better data accessibility",
    link: "https://siscc.org/sdmxai/",
    resourcetype: "Workshop",
    organisation: "OECD, Bank of International Settlements",
    date: "2024-04",
    aimodels: "GPT-3.5, GPT-4",
    approach: "RAG",
    tools: "Stat GPT (IMF), .Stat LLM-based Search POC (SEASE), StatsBot POC (e-Zest), ChatHMS (HMS)",
    codeavailability: "N/A"
},
{
    id: 23,
    usecasetype: "Text generation for analysis",
    worktitle: "ParliAI – using AI tools to monitor parliamentary coverage of the ONS across the UK",
    link: "https://datasciencecampus.ons.gov.uk/parliai-using-ai-tools-to-monitor-parliamentary-coverage-of-the-ons-across-the-uk/",
    resourcetype: "Blog",
    organisation: "UK ONS",
    date: "2024-08",
    aimodels: "Gemini Pro 1.0, Gemma 1.0",
    approach: "Prompte template",
    tools: "Ollama",
    codeavailability: "Yes"
} 
]
